
    
    // "title": "De Luxe Studio",
    // "image": "https://thehoughtonhotel.com/wp-content/uploads/2023/04/LUXURY-APART-HOTEL-STUDIO-700x450.jpg.webp",
    // "image2": "https://thehoughtonhotel.com/wp-content/uploads/2023/04/LUXURY-APART-HOTEL-STUDIO-1-scaled.jpg.webp",
    // "image3": "https://thehoughtonhotel.com/wp-content/uploads/2023/04/LUXURY-APART-HOTEL-STUDIO-KITCHENETTE-scaled.jpg.webp",
    // "image4": "https://thehoughtonhotel.com/wp-content/uploads/2023/04/Luxury-Apart-Hotel-Studio-Bathroom-scaled.jpg.webp",
    // "price": 900,
    // "maxPeople": 2,
    // "desc": "Designed with your needs in mind, our studios provide a cozy and modern atmosphere, equipped with top-notch amenities like high-speed internet and a flat-screen TV. Enjoy the convenience of a well-equipped kitchenette, making it easy to prepare meals at your leisure. ",
    // "util": "Spacious 60m² Studio Apartment",
    // "util1": "1 King Size Bed",
    // "util2": "Fully equipped kitchenette",
    // "util3": "",
    // "util4": "",
    // "util5": "",
    // "roomNumber": 101,
    
    //   "title": "De Luxe King Vista",
    //   "image": "https://thehoughtonhotel.com/wp-content/uploads/2023/03/KING-City-Vista-1-1-scaled.jpg.webp",
    //   "image2": "https://thehoughtonhotel.com/wp-content/uploads/2023/03/KING-Pool-Facing-211-6-scaled.jpg.webp",
    //   "image3": "https://thehoughtonhotel.com/wp-content/uploads/2023/03/KING-Pool-Facing-211-8-scaled.jpg.webp",
    //   "image4": "",
    //   "price": 1000,
    //   "maxPeople": 2,
    //   "desc": "Whether you're a solo traveler seeking privacy or a couple on a getaway, our studio rooms offer a cost-effective solution without compromising on style. Bask in the natural light that pours through large windows, and take in the stunning views of our accessible location. With positive guest reviews and complimentary services, our king suite rooms are the ideal choice for both short-term and extended stays, promising a memorable and comfortable experience.",
    //   "util": "1 King Size Bed",
    //   "util1": "Minibar",
    //   "util2": "Spacious 48m² Suite",
    //   "util3": "Nespresso Machine",
    //   "util4": "Full En-suite Bathroom",
    //   "util5": "",
    //   "roomNumber": 102,
     
  
    //   "title": "De Luxe Penthouse",
    //   "image": "https://thehoughtonhotel.com/wp-content/uploads/2023/04/2-BED-LUXURY-PENTHOUSE-BEDROOM-1-scaled.jpg.webp",
    //   "image2": "https://thehoughtonhotel.com/wp-content/uploads/2023/04/2-BED-LUXURY-PENTHOUSE-LOUNGE-AREA-700x450.jpg.webp",
    //   "image3": "https://thehoughtonhotel.com/wp-content/uploads/2023/04/2-BED-LUXURY-PENTHOUSE-700x450.jpg.webp",
    //   "image4": "https://media.cnn.com/api/v1/images/stellar/prod/160920113031-beachfront-hotel-20-resort-at-pedregal-1.jpg?q=w_1900,h_1069,x_0,y_0,c_fill/h_618",
    //   "price": 1800,
    //   "maxPeople": 2,
    //   "desc": "Indulge in luxury and opulence with our exquisite Penthouse Suite. Designed to cater to the most discerning guests, this lavish retreat offers an unparalleled experience of elegance and sophistication.",
    //   "util": "300m² Penthouse",
    //   "util1": " En-suite Bathroom",
    //   "util2": "Private Hot Tub",
    //   "util3": "Fully Integrated Kitchen",
    //   "util4": "Butler services available",
    //   "util5": "Fully stocked Minibar Inclusive",
    //   "roomNumber": 104,
  
  
    //   "title": "De Luxe Family Room",
    //   "image": "https://image-tc.galaxy.tf/wijpeg-7e6uprnh1y2xrek4eiavsw65e/family-room-suites-overview-2_wide.jpg?crop=0%2C103%2C1980%2C1114&width=1200",
    //   "image2": "https://image-tc.galaxy.tf/wijpeg-7ng0vu8db011ivkzeiidl1yqg/family-room-suites-individual-page-2_wide.jpg?crop=0%2C103%2C1980%2C1114&width=1200",
    //   "image3": "https://image-tc.galaxy.tf/wijpeg-ektzaupt99fjk5swxouhckeha/sprh-family-room-bathroom_wide.jpg?crop=0%2C105%2C2000%2C1125&width=1200",
    //   "image4": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvcugOnjHtH6KT_99ocz-U9sh5XajO2EXJvQ&usqp=CAU",
    //   "price": 2000,
    //   "maxPeople": 6,
    //   "desc": "Book your stay today and give your family the gift of an unforgettable vacation in our spacious and stylish family rooms. Your comfort and satisfaction are our top priorities, and we can't wait to welcome you to a world of luxury and relaxation!",
    //   "util": "1 King Bed and Bunk",
    //   "util1": "Mini-bar and refrigerator",
    //   "util2": "Laundry Service",
    //   "util3": "Thermostatically controlled air conditioning",
    //   "util4": "Standing Shower",
    //   "util5": "Coffee Machine",
    //   "roomNumber": 105
  